### ISSUE TITLE
DHT

### ISSUE THREAD

**Issue by Atraxus** [Atraxus/dit#5]
This issue tracks the implementation of the distributed hash table (DHT). The DHT should map from `DhtAddr` to a list of `SockAddr`.

### API goal

```rust
impl Controller {
    /// Announces that some content is available from the local peer.
    pub async fn dht_publish(&self, content_addr: DhtAddr) -> io::Result<()> { /* ... */ }

    /// Returns a list of addresses where the content is available.
    pub async fn dht_fetch(&self, content_addr: DhtAddr) -> io::Result<Vec<SocketAddr>> { /* ... */ }
}
```

### Steps / History

- [x] basic datatypes: #2
- [x] track connections (fingers): #13
- [x] dht ping, packet forwarding / routing: #21
- [x] actually store data on DHT: #22
- [x] socketbound packets, socket ping: part of #23
- [ ] ~repair if peers leave~
